name: test

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        # clisp doesn't run on ubuntu VMs currently
        lisp: [sbcl-bin,ccl-bin/1.12.2,ecl,allegro/10.1express,cmu-bin/21e,abcl/1.9.2]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      
    - name: cache .roswell
      id: cache-dot-roswell
      uses: actions/cache@v3
      with:
        path: ~/.roswell
        key: ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
        restore-keys: |
          ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-
          ${{ runner.os }}-dot-roswell-

    - name: install roswell
      env:
       LISP: ${{ matrix.lisp }}
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: install parachute
      run: |
        ros install parachute
        echo "$HOME/.roswell/bin" >> $GITHUB_PATH

    - name: update ql dist if we have one cached
      shell: bash
      run: ros -e "(ql:update-all-dists :prompt nil)"

    - name: load code and run tests
      shell: bash
      run: |
        run-parachute -l "random-state-test" "org.shirakumo.random-state.test"
